[[language]]
name = "go"
auto-format = true

[[language]]
name = "python"
auto-format = true

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "lua"
roots = [".luarc.json"]
auto-format = true

[[language]]
name = "markdown"
text-width = 80

[language.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""
